### ISSUE TITLE
Activation throws fatal error for array_key_exists argument 2 is boolean

### ISSUE THREAD

**Issue by jakeparis** [toolstack/cyan-backup#1]
Hello, 
I'd like to give this plugin a try, but upon activation I'm receiving the following error. 
I'm running on WordPress 6.4.2, PHP version 8.1.

```
[25-Jan-2024 20:08:35 UTC] PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array)
 must be of type array, bool given in /htdocs/wp-content/plugins/cyan-backup/c
yan-backup.php:85
Stack trace:
#0 /htdocs/wp-content/plugins/cyan-backup/cyan-backup.php(1615): CYANBackup->_
_construct()
#1 /htdocs/wp-admin/includes/plugin.php(2318): include_once('/shared/httpd/j..
.')
#2 /htdocs/wp-admin/includes/plugin.php(663): plugin_sandbox_scrape('cyan-back
up/cya...')
#3 /htdocs/wp-admin/plugins.php(58): activate_plugin('cyan-backup/cya...', 'ht
tps://jakepar...', false)
#4 {main}
  thrown in /htdocs/wp-content/plugins/cyan-backup/cyan-backup.php on line 85
```

**Comment by sajad-ahmadi** [comment]
Hello,
In the root path of the plugin, open the file with the name `cyan-backup.php` and go to line 85, which you can see (a piece of code or condition) as shown below.

```
if( array_key_exists( 'version', $options ) && $options['version'] != self::VERSION )
    {
         // code
    }
```
Change (a piece of code or condition) above to below, which `is_array($options)` is added at the beginning


```
if( is_array($options) && array_key_exists( 'version', $options ) && $options['version'] != self::VERSION )
    {
        // code
    }
```

**Comment by jakeparis** [comment]
No, all that is needed it to change line 82 from
```
$options = get_option( $this->option_name );
```
to
```
$options = get_option( $this->option_name , array() );
```

Thus providing a default argument to `get_options()` to ensure that $options is always an array, even if no options are setup yet. I was going to submit a PR with this and a few other changes, but I abandoned that idea because I couldn't really get the plugin to work for me.

**Comment by toolstack** [comment]
Thanks for the fix, I've committed it and pushed a new release out.
